version: '3.8'

# Version de développement - SQLite uniquement
services:
  # API Backend
  duel-api:
    build:
      context: ./duel-api
      dockerfile: Dockerfile
    container_name: duel-api-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      DOCKER_ENV: "true"
      ALLOWED_ORIGINS: "http://localhost:5173,http://localhost:3000"
      DATABASE_URL: "file:./dev.db"
    ports:
      - "3001:3000"
    volumes:
      # Bind mount pour le développement
      - ./duel-api:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - duel-network

  # Frontend React
  duel-frontend:
    build:
      context: ./duel-frontend
      dockerfile: Dockerfile
    container_name: duel-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - duel-api
    networks:
      - duel-network

networks:
  duel-network:
    driver: bridge